Insert into ZMS_KJO_LOC_RESTRICTION
   (LOCATION, SOURCE_DESTINATION, IMS_TRAN_TYPE, TRAN_CATEGORY, ACTIVE_FLAG, 
    CREATE_DATE)
 Values
   (8460, 'SOURCE', '14', 'SHIP', 'Y', 
    TO_DATE('06/28/2026 21:52:49', 'MM/DD/YYYY HH24:MI:SS'));
Insert into ZMS_KJO_LOC_RESTRICTION
   (LOCATION, SOURCE_DESTINATION, IMS_TRAN_TYPE, TRAN_CATEGORY, ACTIVE_FLAG, 
    CREATE_DATE)
 Values
   (8415, 'SOURCE', '14', 'SHIP', 'Y', 
    TO_DATE('06/28/2026 21:52:49', 'MM/DD/YYYY HH24:MI:SS'));
COMMIT;
